In [2]:
import numpy as np
arr= np.array([1, 2, 3, 4, 5])

In [7]:
type(arr)
print(arr.shape)

(5,)


In [9]:
arr.reshape((1,5))

array([[1, 2, 3, 4, 5]])

In [12]:
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])

In [17]:
print(arr2.shape)

(2, 5)


In [25]:
new = np.arange(0,10,2).reshape((1,5))

In [26]:
new

array([[0, 2, 4, 6, 8]])

In [28]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
# identty matri x
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
# numpy vecotuszed oerations
new = np.arange(0,20,2).reshape(2,5)

In [39]:
print(np.sqrt(new))

[[0.         1.41421356 2.         2.44948974 2.82842712]
 [3.16227766 3.46410162 3.74165739 4.         4.24264069]]


In [41]:
# slicing and indexing
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [66]:
arr

array([[100, 101, 100],
       [  4,   5,   6],
       [  7,   8,   9]])

In [61]:
# arr[1::]
arr[1:,2:]
arr[0:2,1 :]

array([[2, 3],
       [5, 6]])

In [65]:
# modify arr elemet
arr[0][1]=101

In [68]:
# statactical concept normalization 

#  to have a mean of zero and standar deviation 
arr - arr.mean()
arr / arr.std()
# mean mode median  variance, and standar deviation 






In [73]:
# logcial operation 
data =np.array( [1,2,3,4,5,6,7,8,9,10])


In [81]:
data >5
data[(data> 5 ) &  (data < 2)]

array([], dtype=int64)